/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "foo.h"

std::string foo::Greeter::greeting() {
    return std::string("Hello, World!");
}
