/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef FOO_H
#define FOO_H

#ifdef _WIN32
#define FOO_EXPORT_FUNC __declspec(dllexport)
#else
#define FOO_EXPORT_FUNC
#endif

#include <string>

namespace foo {
    class Greeter {
        public:
        std::string FOO_EXPORT_FUNC greeting();
    };
}

#endif
